services:
  - type: web
    name: tsgarmyweb-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 12h
      - key: SUPER_ADMIN_USERNAME
        sync: false
      - key: SUPER_ADMIN_PASSWORD
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: ADMIN_URL
        sync: false
      - key: TRUST_PROXY
        value: "1"
